server:
  port: 8081

spring:
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USER:guest}"
    password: "${RABBITMQ_PASS:guest}"

  mail:
    host: "${MAIL_HOST:mailhog}"
    port: "${MAIL_PORT:1025}"
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  rabbit:
    item:
      queue: "${ITEM_QUEUE:itemQueue}"
