server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:producer_db}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"

app:
  rabbit:
    item:
      exchange: "${ITEM_EXCHANGE:itemDirectExchange}"
      routing-key: "${ITEM_ROUTING_KEY:itemKey}"
      name-queue: "${ITEM_QUEUE:itemQueue}"
    card:
      exchange: "${CARD_EXCHANGE:cardTopicExchange}"
      routing-key: "${CARD_ROUTING_KEY:card.new}"
      routing-key-template: "${CARD_TEMPLATE_ROUTING_KEY:card.*}"
      name-queue: "${CARD_QUEUE :cardQueue}"
